version: '3.1'
services:

  slicer:
    build: ./
    image: home.4it.me:5000/ofc-slicer:latest
    volumes:
      - ../uploads:/app/uploads
    environment:
      ADMIN_AUTH_TOKEN: ${ADMIN_AUTH_TOKEN}
      STL_DIR: /app/uploads
